CREATE TABLE "mf_scheme_category" (
	"category_code" integer PRIMARY KEY NOT NULL,
	"category_name" text NOT NULL,
	CONSTRAINT "mf_scheme_category_category_name_unique" UNIQUE("category_name")
);
--> statement-breakpoint
ALTER TABLE "benchmark" ALTER COLUMN "benchmark_code" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "benchmark_benchmark_code_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "mf_schemes" ADD COLUMN "category_code" integer;--> statement-breakpoint
ALTER TABLE "mf_schemes" ADD CONSTRAINT "mf_schemes_category_code_mf_scheme_category_category_code_fk" FOREIGN KEY ("category_code") REFERENCES "public"."mf_scheme_category"("category_code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "benchmark" ADD CONSTRAINT "benchmark_benchmark_name_unique" UNIQUE("benchmark_name");