ALTER TABLE "mf_schemes" RENAME COLUMN "base_currency" TO "currency";--> statement-breakpoint
ALTER TABLE "mf_schemes" RENAME COLUMN "domicile_country" TO "country";--> statement-breakpoint
ALTER TABLE "mf_schemes" DROP CONSTRAINT "mf_schemes_base_currency_currency_currency_code_fk";
--> statement-breakpoint
ALTER TABLE "mf_schemes" DROP CONSTRAINT "mf_schemes_domicile_country_country_country_code_fk";
--> statement-breakpoint
DROP INDEX "unique_mf_schemes_key";--> statement-breakpoint
ALTER TABLE "mf_scheme_category" ALTER COLUMN "category_code" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "mf_scheme_category_category_code_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "mf_schemes" ADD CONSTRAINT "mf_schemes_currency_currency_currency_code_fk" FOREIGN KEY ("currency") REFERENCES "public"."currency"("currency_code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mf_schemes" ADD CONSTRAINT "mf_schemes_country_country_country_code_fk" FOREIGN KEY ("country") REFERENCES "public"."country"("country_code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "unique_isin_amc_scheme_category_idx" ON "mf_schemes" USING btree ("isin","amc_code","category_code");--> statement-breakpoint
CREATE INDEX "isin_amc_idx" ON "mf_schemes" USING btree ("isin","amc_code");